all: safeadd.out safesubtract.out safemultiply.out safedivide.out

safeadd.out: safeint.h safeadd.c safeint.o
	gcc safeadd.c safeint.o -o safeadd.out

safesubtract.out: safeint.h safesubtract.c safeint.o
	gcc safesubtract.c safeint.o -o safesubtract.out

safemultiply.out: safeint.h safemultiply.c safeint.o
	gcc safemultiply.c safeint.o -o safemultiply.out

safedivide.out: safeint.h safedivide.c safeint.o
	gcc safedivide.c safeint.o -o safedivide.out

safeint.o: safeint.h
	gcc safeint.c -c safeint.o

clean:
	rm *.o
	rm *.out

